---

- hosts: all
  name: 'Converge'
  become: True

  tasks:
    - import_role:
        name: 'ansible-role-linux_kernel_module'
      vars:
        linux_kernel_modules:
          - name: 'ip_tables'
            state: 'present'
            params: {}

          - name: 'ip6_tables'
            state: 'present'
            params: {}
